// Privacy Policy content ported from LegalDocumentView.swift's `MChajaLegalContent`;
// Terms & Conditions content ported from MChajaTermsContent.swift (the two were
// byte-identical placeholders until a distinct Terms document was supplied). Only
// English is ported so far for either document, matching the English-first
// convention already established in i18n.ts; the other 15 languages are future work.
export type LegalBlock =
  | { type: "heading"; text: string }
  | { type: "subheading"; text: string }
  | { type: "body"; text: string }
  | { type: "bullet"; text: string }
  | { type: "divider" };

function heading(text: string): LegalBlock {
  return { type: "heading", text };
}
function subheading(text: string): LegalBlock {
  return { type: "subheading", text };
}
function body(text: string): LegalBlock {
  return { type: "body", text };
}
function bullet(text: string): LegalBlock {
  return { type: "bullet", text };
}
const divider: LegalBlock = { type: "divider" };

export const LEGAL_EFFECTIVE_DATE = "August 7, 2026";

export const privacyBlocksEn: LegalBlock[] = [
  heading("M-Chaja™ Privacy Policy"),
  body("Welcome to M-Chaja™."),
  body(
    "M-Chaja™ (“the App”) is owned and operated by BANG Digital Limited (“we,” “our,” or “us”). Your privacy is important to us. This Privacy Policy explains how we collect, use, store, and protect your personal information when you use the M-Chaja™ mobile application and our power bank rental services.",
  ),
  body("By using the App, you agree to the practices described in this Privacy Policy."),
  divider,
  heading("1. Information We Collect"),
  body("We may collect the following information:"),
  subheading("Personal Information"),
  bullet("Full name"),
  bullet("Phone number"),
  bullet("Email address (if provided)"),
  bullet("National ID number (where required for verification)"),
  bullet("Profile photo (optional)"),
  subheading("Account Information"),
  bullet("Login credentials"),
  bullet("Customer ID"),
  bullet("Account preferences"),
  subheading("Payment Information"),
  body("We may collect payment transaction details such as:"),
  bullet("Mobile money payments"),
  bullet("Card payment references"),
  bullet("Transaction history"),
  body("Note: We do not store your mobile money PINs, card PINs, or banking passwords."),
  subheading("Rental Information"),
  bullet("Rental history"),
  bullet("Active rentals"),
  bullet("Return history"),
  bullet("Station usage"),
  bullet("Rental duration"),
  subheading("Device Information"),
  body("We may automatically collect:"),
  bullet("Device model"),
  bullet("Operating system"),
  bullet("App version"),
  bullet("Device identifiers"),
  bullet("IP address"),
  subheading("Location Information"),
  body("With your permission, M-Chaja™ may access your location to help you find nearby charging stations."),
  body("You may disable location permissions at any time, although some features may not function correctly."),
  divider,
  heading("2. How We Use Your Information"),
  body("We use your information to:"),
  bullet("Create and manage your account"),
  bullet("Process rentals"),
  bullet("Process payments"),
  bullet("Locate nearby M-Chaja™ stations"),
  bullet("Improve our services"),
  bullet("Prevent fraud"),
  bullet("Verify customer identity"),
  bullet("Provide customer support"),
  bullet("Send important service notifications"),
  bullet("Comply with legal obligations"),
  divider,
  heading("3. Sharing Your Information"),
  body("We do not sell your personal information."),
  body("We may share information with:"),
  bullet("Payment service providers"),
  bullet("Mobile network operators"),
  bullet("Identity verification providers"),
  bullet("Cloud hosting providers"),
  bullet("Law enforcement agencies when required by law"),
  bullet("Regulatory authorities"),
  body("All third-party service providers are required to protect your information."),
  divider,
  heading("4. Data Security"),
  body(
    "We use reasonable administrative, technical, and physical safeguards to protect your personal information from unauthorized access, disclosure, alteration, or destruction.",
  ),
  body("Although we strive to protect your information, no method of electronic transmission or storage is completely secure."),
  divider,
  heading("5. Data Retention"),
  body("We retain your information only for as long as necessary to:"),
  bullet("Provide our services"),
  bullet("Meet legal and regulatory requirements"),
  bullet("Resolve disputes"),
  bullet("Enforce our agreements"),
  body("When information is no longer required, it is securely deleted or anonymized."),
  divider,
  heading("6. Your Rights"),
  body("Subject to applicable law, you may have the right to:"),
  bullet("Access your personal information"),
  bullet("Correct inaccurate information"),
  bullet("Request deletion of your account"),
  bullet("Withdraw consent where applicable"),
  bullet("Object to certain processing activities"),
  bullet("Request a copy of your personal data"),
  body("Requests may be submitted through our customer support channels."),
  divider,
  heading("7. Children’s Privacy"),
  body("M-Chaja™ is not intended for children under the age of 18."),
  body("We do not knowingly collect personal information from minors."),
  divider,
  heading("8. Cookies and Analytics"),
  body("The App may use analytics technologies to understand how users interact with the service and to improve the user experience."),
  body("These technologies do not collect your mobile money PIN or banking credentials."),
  divider,
  heading("9. Third-Party Services"),
  body("The App may integrate with third-party services including:"),
  bullet("Mobile money providers"),
  bullet("Payment gateways"),
  bullet("Mapping services"),
  bullet("Analytics providers"),
  bullet("Push notification services"),
  body("These services operate under their own privacy policies."),
  divider,
  heading("10. Changes to this Privacy Policy"),
  body("We may update this Privacy Policy from time to time."),
  body(
    "Any changes will be published within the App and on our official website. Continued use of the App after changes become effective constitutes acceptance of the updated Privacy Policy.",
  ),
  divider,
  heading("11. Contact Us"),
  body("If you have any questions regarding this Privacy Policy, please contact us:"),
  body("BANG Digital Limited"),
  body("Email: support@m-chaja.com"),
  body("Website: www.mchaja.co.tz"),
  body("Customer Support: Available through the M-Chaja™ mobile application."),
  divider,
  body(
    "By using M-Chaja™, you acknowledge that you have read and understood this Privacy Policy and agree to the collection and use of your information as described above.",
  ),
];

export const termsBlocksEn: LegalBlock[] = [
  body(
    "Welcome to M-Chaja™, a portable power bank rental service owned and operated by BANG Digital Limited (“M-Chaja”, “we”, “our”, or “us”).",
  ),
  body(
    "These Terms & Conditions govern your access to and use of the M-Chaja™ mobile application, website, self-service charging stations, and related services. By creating an account or using M-Chaja™, you agree to be bound by these Terms.",
  ),
  divider,
  heading("1. Eligibility"),
  body("To use M-Chaja, you must:"),
  bullet("Be at least 18 years old or have the consent of a parent or legal guardian where permitted by law."),
  bullet("Provide accurate and complete registration information."),
  bullet("Maintain the confidentiality of your account credentials."),
  bullet("Be legally capable of entering into a binding agreement."),
  body("You are responsible for all activities conducted through your account."),
  divider,
  heading("2. Account Registration"),
  body("To rent a power bank, you must create an M-Chaja™ account."),
  body("You agree to:"),
  bullet("Provide true, accurate, and current information."),
  bullet("Keep your information up to date."),
  bullet("Notify us immediately if your account has been compromised."),
  body("We reserve the right to suspend or terminate accounts containing false or misleading information."),
  divider,
  heading("3. Renting a Power Bank"),
  body("A rental begins when a power bank is successfully released from an M-Chaja™ station."),
  body(
    "The rental ends only when the power bank is successfully returned to an authorised M-Chaja™ station and the return is confirmed in the app.",
  ),
  body("You are responsible for the power bank throughout the rental period."),
  divider,
  heading("4. Rental Charges"),
  body("Rental fees are displayed in the M-Chaja™ app before each rental."),
  body("By confirming a rental, you agree to the applicable:"),
  bullet("Rental charges"),
  bullet("Deposits (where applicable)"),
  bullet("Late return fees"),
  bullet("Damage or replacement fees (if applicable)"),
  body("All fees are non-refundable except where required by law."),
  divider,
  heading("5. Returning the Power Bank"),
  body("You agree to:"),
  bullet("Return the power bank to an operational M-Chaja™ station."),
  bullet("Ensure the power bank is securely inserted into the docking slot."),
  bullet("Confirm the successful return through the app."),
  body("A rental remains active until the return is successfully recorded."),
  divider,
  heading("6. Lost, Stolen, or Damaged Power Banks"),
  body("You are responsible for the power bank while it is rented under your account."),
  body("If a power bank is:"),
  bullet("Lost"),
  bullet("Stolen"),
  bullet("Intentionally damaged"),
  bullet("Not returned within the maximum rental period"),
  body("M-Chaja reserves the right to charge the applicable replacement or repair fee."),
  divider,
  heading("7. Acceptable Use"),
  body("You agree not to:"),
  bullet("Tamper with or dismantle the power bank or charging station."),
  bullet("Use the equipment for unlawful purposes."),
  bullet("Damage, vandalise, or misuse M-Chaja™ property."),
  bullet("Attempt to bypass payment or security systems."),
  bullet("Share your account with another person."),
  body("Violation of these terms may result in account suspension, termination, or legal action."),
  divider,
  heading("8. Payments"),
  body("Payments may be made using supported payment methods available within the M-Chaja™ app."),
  body("You authorise M-Chaja™ to collect any applicable rental fees, penalties, or outstanding balances associated with your account."),
  divider,
  heading("9. Availability of Service"),
  body("While we strive to provide uninterrupted service, we do not guarantee that:"),
  bullet("Every charging station will always be operational."),
  bullet("Power banks will always be available."),
  bullet("The app will be free from interruptions or technical issues."),
  body("Service availability may be affected by maintenance, connectivity issues, or unforeseen events."),
  divider,
  heading("10. Limitation of Liability"),
  body("To the fullest extent permitted by law, M-Chaja™ shall not be liable for:"),
  bullet("Loss of business or income."),
  bullet("Loss of data."),
  bullet("Missed appointments due to device battery depletion."),
  bullet("Indirect, incidental, or consequential damages arising from the use of our services."),
  body("Our total liability shall not exceed the amount paid by you for the relevant rental, except where otherwise required by law."),
  divider,
  heading("11. Intellectual Property"),
  body("All content within the M-Chaja™ app, including:"),
  bullet("Logos"),
  bullet("Trademarks"),
  bullet("Software"),
  bullet("Designs"),
  bullet("Images"),
  bullet("Text"),
  body("remains the property of BANG Digital Limited and may not be copied or reproduced without prior written permission."),
  divider,
  heading("12. Privacy"),
  body("Your use of M-Chaja™ is also governed by our Privacy Policy, which explains how we collect, use, and protect your personal information."),
  divider,
  heading("13. Suspension or Termination"),
  body("We may suspend or terminate your account if you:"),
  bullet("Breach these Terms."),
  bullet("Fail to pay applicable charges."),
  bullet("Engage in fraudulent or illegal activity."),
  bullet("Misuse M-Chaja™ equipment or services."),
  body("Termination does not release you from any outstanding financial obligations."),
  divider,
  heading("14. Changes to These Terms"),
  body("We may update these Terms & Conditions from time to time."),
  body(
    "Updated versions will be published in the app and on our official website. Continued use of the service after changes become effective constitutes acceptance of the revised Terms.",
  ),
  divider,
  heading("15. Governing Law"),
  body("These Terms & Conditions shall be governed by and interpreted in accordance with the laws of the United Republic of Tanzania."),
  body("Any disputes arising from these Terms shall be subject to the jurisdiction of the competent courts of Tanzania."),
  divider,
  heading("16. Contact Information"),
  body("For questions regarding these Terms & Conditions, please contact:"),
  body("BANG Digital Limited"),
  body("Email: support@mchaja.co.tz"),
  body("Website: www.mchaja.co.tz"),
  body("Customer Support: Available through the M-Chaja™ mobile application."),
  divider,
  body(
    "By creating an account, renting a power bank, or using any M-Chaja™ service, you acknowledge that you have read, understood, and agreed to these Terms & Conditions.",
  ),
];
